### ISSUE TITLE
Incompatibility with Redstone Armory

### ISSUE THREAD

**Issue by ate0ate** [SleepyTrousers/EnderCore#4] opened 2015-06-28 14:30 UTC
I understand that ttCore is replaced with EnderCore, but unfortunately Redstone Armory is dependent on ttCore and I don't think that will change while EnderCore is in alpha/beta. I have been using ttCore and EnderCore side by side for a while now without issue, I just simply disabled most everything in the ttCore configs. My question is, is there any way to provide a config option or something to allow these two to play nicely, or am I going to have to remove Redstone Armory for the time being?

**Comment by MatthiasMann** [comment] 2015-06-28 14:33
Duplicate of #2

**Closed by MatthiasMann** 2015-06-28 14:33 UTC
Labels: duplicate
